### ISSUE TITLE
issue: encountering error when running test cases

### ISSUE THREAD

**Issue by 5yndr0m** [DisasterWatchHQ/disasterCatcher#12]
```
console.error
      Error creating admin log: Error: AdminLog validation failed: target_type: 'invalid_type' is not a valid enum value for path 'target_type'.
          at ValidationError.inspect (/home/syndrom/Documents/DisasterWatch/project/disasterCatcher/node_modules/mongoose/lib/error/validation.js:52:26)
          at formatValue (node:internal/util/inspect:814:19)
          at inspect (node:internal/util/inspect:373:10)
          at formatWithOptionsInternal (node:internal/util/inspect:2315:40)
          at format (node:internal/util/inspect:2172:10)
          at console.error (/home/syndrom/Documents/DisasterWatch/project/disasterCatcher/node_modules/@jest/console/build/BufferedConsole.js:127:43)
          at error (/home/syndrom/Documents/DisasterWatch/project/disasterCatcher/controllers/adminLogsController.js:20:13)
          at call (/home/syndrom/Documents/DisasterWatch/project/disasterCatcher/controllers/adminLogsController.js:2:1)
          at Generator.tryCatch (/home/syndrom/Documents/DisasterWatch/project/disasterCatcher/controllers/adminLogsController.js:2:1)
          at Generator._invoke [as throw] (/home/syndrom/Documents/DisasterWatch/project/disasterCatcher/controllers/adminLogsController.js:2:1)
          at asyncGeneratorStep (/home/syndrom/Documents/DisasterWatch/project/disasterCatcher/controllers/adminLogsController.js:2:1)
          at asyncGeneratorStep (/home/syndrom/Documents/DisasterWatch/project/disasterCatcher/controllers/adminLogsController.js:2:1)
          at processTicksAndRejections (node:internal/process/task_queues:105:5) {
        errors: {
          target_type: ValidatorError: 'invalid_type' is not a valid enum value for path 'target_type'.
              at validate (/home/syndrom/Documents/DisasterWatch/project/disasterCatcher/node_modules/mongoose/lib/schemaType.js:1385:13)
              at SchemaString.Object.<anonymous>.SchemaType.doValidate (/home/syndrom/Documents/DisasterWatch/project/disasterCatcher/node_modules/mongoose/lib/schemaType.js:1369:7)
              at /home/syndrom/Documents/DisasterWatch/project/disasterCatcher/node_modules/mongoose/lib/document.js:3071:18
              at processTicksAndRejections (node:internal/process/task_queues:85:11) {
            properties: [Object],
            kind: 'enum',
            path: 'target_type',
            value: 'invalid_type',
            reason: undefined,
            [Symbol(mongoose#validatorError)]: true
          }
        },
        _message: 'AdminLog validation failed'
      }

      18 |     return log;
      19 |   } catch (error) {
    > 20 |     console.error('Error creating admin log:', error);
         |             ^
      21 |     return null;
      22 |   }
      23 | };

      at error (controllers/adminLogsController.js:20:13)
      at call (controllers/adminLogsController.js:2:1)
      at Generator.tryCatch (controllers/adminLogsController.js:2:1)
      at Generator._invoke [as throw] (controllers/adminLogsController.js:2:1)
      at asyncGeneratorStep (controllers/adminLogsController.js:2:1)
      at asyncGeneratorStep (controllers/adminLogsController.js:2:1)
```
I suspect this has to do something with admincontrollers logging function

**Comment by 5yndr0m** [comment]
I changed the admin_log_create function to check whether target_types were mapped before the creation of logs. this might be the fix for the issue. need to test the changes before moving forward.
