### ISSUE TITLE
new user registration failing

### ISSUE THREAD

**Issue by 5yndr0m** [DisasterWatchHQ/disasterCatcher#8]
When trying to register a new user account following error occurs :

`Auth Error: TypeError: Cannot read properties of undefined (reading 'pseudoUser')
    at protectRoute (file:///home/syndrom/Documents/DisasterWatch/project/disasterCatcher/middlewares/authMiddleware.js:16:24)
    at Layer.handle [as handle_request] (/home/syndrom/Documents/DisasterWatch/project/disasterCatcher/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/syndrom/Documents/DisasterWatch/project/disasterCatcher/node_modules/express/lib/router/index.js:328:13)
    at /home/syndrom/Documents/DisasterWatch/project/disasterCatcher/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/syndrom/Documents/DisasterWatch/project/disasterCatcher/node_modules/express/lib/router/index.js:346:12)
    at next (/home/syndrom/Documents/DisasterWatch/project/disasterCatcher/node_modules/express/lib/router/index.js:280:10)
    at Function.handle (/home/syndrom/Documents/DisasterWatch/project/disasterCatcher/node_modules/express/lib/router/index.js:175:3)
    at router (/home/syndrom/Documents/DisasterWatch/project/disasterCatcher/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/home/syndrom/Documents/DisasterWatch/project/disasterCatcher/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/syndrom/Documents/DisasterWatch/project/disasterCatcher/node_modules/express/lib/router/index.js:328:13)
POST /api/user/register 401 38.034 ms - 45`

possibly cause : routing issue

**Comment by ukmuniweera** [comment]
A fix has been pushed.

**Comment by 5yndr0m** [comment]
fix tested and confirmed
